Milestone 5: Event Handlers
taiwocoker/React-Calculator pull request #5
Opened 2020-10-05 11:29 UTC by taiwocoker

In this milestone:
- I implemented click handler in ButtonPanel and Button component
- I implemented the render function in the App component
- I implemented props drilling passing the handle click function from App.js to button.js

2020-10-05 13:42 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi @taiwocoker :hand: 
Awesome work on this milestone so far :clap: :+1: 
We only need to make some changes before moving on :smile: 

- [ ] We need to deal with division by 0. Right now the app throws an error.

- [ ] I notice a bug in your application, it seems sometimes the calculator does not work as expected and the result button does not show the result of the operation. I must emphasize however that this is not always the case, sometimes works as expected, sometimes don't
![bug1](https://user-images.githubusercontent.com/30977845/95086154-87808380-06f6-11eb-9e88-317438ba3c66.gif)

Feel free to message me on slack if you have any questions :smile: 
Happy Coding :computer: 
**Sergio Torres**

2020-10-05 13:42 UTC, Torres-ssf commented on src/components/App.js
> +// eslint-disable-next-line no-unused-vars
- [ ] We can safely remove this eslint disable line since you do not have any unused vars here.

2020-10-06 14:31 UTC, mikenath223 requested changes
### Hi @taiwocoker 👋

**You've done quite well on this.👍**


**STATUS: CHANGES REQUIRED. 👷‍♀️**

- [ ] However, consider the fact that it would improve user experience if the result from a previous calculation could be used as the first input for the next calculation. Kindly add that feature.
![chrome-capture](https://user-images.githubusercontent.com/33323077/95214789-2d5feb00-07e8-11eb-9be0-69018506ad55.gif)

- [ ] In addition, as requested in the previous review kindly fix [this issue](https://github.com/taiwocoker/React-Calculator/pull/5#discussion_r499608012).

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-10-06 23:07 UTC, shloch approved these changes
## Hello @taiwocoker , 

Great job......points from former TSEs have been taken into consideration
Keep up with the good work
![calc](https://user-images.githubusercontent.com/40712459/95269334-1abdd400-0831-11eb-9831-5b162e90de99.gif)

It's thumbs up for me

2020-10-14 10:28 UTC, merged